### ISSUE TITLE
DOC: Code snippets appear as grey text on a black background

### ISSUE THREAD

**Issue by arm61** [bjmorgan/python_in_chemistry#1]
Need to work out what part of the CSS to change such that the code snippets are more clear. 

See pythoninchemistry.org/functions for an example. 

The aim would be to change the colours to make it more readable. 

I have played around with some of the CSS files and compiled them to no avail.

**Comment by bjmorgan** [comment]
I just had a quick look, and can't figure out where that css is set. It doesn't appear to be in any of the css files in `web/assets`.

**Comment by arm61** [comment]
yeah -- I have a feeling that it is related to the highlight.js thing that is imported in the _layout/default.html file. Unfortunately, the documentation on this js isn't super clear.

**Comment by bjmorgan** [comment]
I think you're right. That external css file defines various `.hljs` attributes, which I think are then used in the external JS script here: http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js

**Comment by bjmorgan** [comment]
Any idea how I can test changes to the css locally, without pushing to github on the master branch?

**Comment by bjmorgan** [comment]
Hmmm. This definitely reminds me of trying to figure out web programming 10 years ago, just with more onion layers of web tools (I've just been installing node, so that I can install gulp, so that I can have my css for my syntax highlighting (from another javascript script) end up in the correct directory).

**Comment by arm61** [comment]
Haha, I had that exact thing before Xmas when I started this. 

You can build locally with:

```bundle exec jekyll serve``` 

And then opening the local link that it give you. 

I will look again at this this evening -- hopefully fresh eyes will help.

**Comment by bjmorgan** [comment]
I've made progress (although it seems to still be cacheing the old version on Github.io). The syntax highlighting css and js scripts are now local. The chief offender with the black background is in the `screen.css` for the `pre` setting. Getting things to look nice will mean playing with the `screen.css` and `rainbow.css`, which contains the syntax highlighting css.

**Comment by arm61** [comment]
Awesome that looks fixed on the github.io now. 

Nice one, gonna close this now.
